# Generated by Django 5.2.4 on 2025-10-15 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier_name', models.CharField(max_length=255)),
                ('carrier_usdot_mc', models.CharField(max_length=255)),
                ('carrier_phone', models.CharField(max_length=50)),
                ('agreement_date', models.DateField()),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('signer_full_name', models.CharField(blank=True, max_length=255)),
                ('signer_title', models.CharField(blank=True, max_length=255)),
                ('signer_email', models.EmailField(blank=True, max_length=254)),
                ('signature_text', models.CharField(blank=True, max_length=1024)),
                ('deposit_method', models.CharField(blank=True, max_length=100)),
                ('accepted_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
