# Generated by Django 5.2.4 on 2025-10-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieragreement',
            name='account_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='carrieragreement',
            name='carrier_phone',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carrieragreement',
            name='carrier_usdot_mc',
            field=models.IntegerField(max_length=255),
        ),
    ]
