# Generated by Django 5.2.4 on 2025-10-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0003_carrieragreement_carrier_usdot_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrieragreement',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
