# Generated by Django 5.2.7 on 2025-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0004_carrieragreement_signature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrieragreement',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name='Signature Image'),
        ),
    ]
