# Generated by Django 5.2.7 on 2025-10-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agreements', '0005_alter_carrieragreement_signature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrieragreement',
            name='signature_image',
        ),
    ]
